scenarios_dir = "D:\ACADEMICS\\SEM-10\\ddp\\datasets\\DDoS_Botnet\\DDoSdata\\"
attacks_dir = "D:\\ACADEMICS\\SEM-10\\ddp\\SecureIoT\\NetSentinel\\dataset_wise_results\\DDoS_Botnet\\attacks\\"
data_dir = "D:\\ACADEMICS\\SEM-10\\ddp\\SecureIoT\\NetSentinel\\dataset_wise_results\\DDoS_Botnet\\data\\"
experiments_dir = "D:\\ACADEMICS\\SEM-10\\ddp\\SecureIoT\\NetSentinel\\dataset_wise_results\\DDoS_Botnet\\experiments\\"
log_file_path = "D:\\ACADEMICS\\SEM-10\\ddp\\SecureIoT\\NetSentinel\\dataset_wise_results\\DDoS_Botnet\\logs\\"